server:
  port: 8080

# JDBC配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8
    username: root
    password: root


#mybatis的相关配置
mybatis:
  #m apper配置文件
  mapper-locations: classpath:mapper/*.xml
  # xml 中 resultType 返回值中包的位置.
  type-aliases-package: com.cy.template.ssm.entry
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true